/* ============ ML.i18n — AUTO EDIT studio dictionary (zh default) ============ */
ML.i18n = (function(){
  const DICT = {
    en: {
      'app.name':'VIDEO LAB','app.tag':'AUTO EDIT',
      'nav.projects':'Projects','nav.assets':'Assets','nav.new':'New Edit','nav.settings':'Settings',
      'cmd.search':'Search commands…','cmd.save':'Save project','cmd.export':'Export project','cmd.openRecent':'Open recent project','cmd.lang':'Switch language',
      'home.title':'Create a video.','home.sub':'Script + Media → Automatically edited.','home.newProj':'Start New Project','home.recent':'Recent Projects','home.empty':'No projects yet.','home.emptySub':'Start your first edit.','home.start':'Start your first edit',
      'home.how':'HOW IT WORKS','home.h1':'01 · Add your script','home.h1d':'Paste any copy — we split it into scenes.','home.h2':'02 · Add your media','home.h2d':'Drop videos, images or audio.','home.h3':'03 · Auto Edit','home.h3d':'We match, cut, voice and subtitle automatically.',
      'proj.open':'Open','proj.dup':'Duplicate','proj.del':'Delete','proj.untitled':'Untitled Project','proj.thumb':'No preview','proj.badData':'Project failed to load','proj.delToast':'Project deleted','proj.dupToast':'Project duplicated',
      'create.title':'Create New Edit','create.name':'Project Name','create.ratio':'Ratio','create.ratio.hint':'9:16 is recommended for feeds (Douyin / Reels / Shorts / 视频号)','create.start':'Create Project',
      'step.script':'SCRIPT','step.media':'MEDIA','step.voice':'VOICE','step.auto':'AUTO EDIT','step.workspace':'WORKSPACE',
      'sc.paste':'Paste your script','sc.placeholder':'Paste your script here…\n\nWhy do many people feel tired even after sleeping 8 hours?\nThe first reason is poor sleep quality.\nThe second is that working long hours keeps the brain from resting.\nSo the real key is sleep quality, not just more hours.','sc.analyze':'Analyze Script','sc.scene':'Scene','sc.keywords':'Keywords','sc.intent':'Intent','sc.visual':'Visual need','sc.dur':'Duration','sc.editText':'Edit script','sc.noScenes':'No scenes yet — paste a script and run Analyze Script.',
      'media.title':'Your Media','media.drop':'Drop files here','media.dropSub':'MP4 · MOV · WebM · JPG · PNG · WebP · MP3 · WAV','media.upload':'Upload Media','media.list':'Media Library','media.selected':'Selected','media.analyze':'Analyze Media','media.analyzing':'Analyzing…','media.noAssets':'No media yet. Drop files or click Upload.','media.asset':'Asset','media.basic':'Basic','media.semantic':'Semantic','media.tags':'Tags','media.mock':'DEV MOCK analysis','media.notConfig':'AI analysis is not configured. Configure it in Settings.','media.preview':'Preview','media.remove':'Remove','media.error.size':'File too large (max 200MB for video, 50MB for image/audio).','media.error.type':'Unsupported format.','media.error.read':'Could not read this file — it may be corrupted.','media.analyzeDone':'Media analyzed','media.dragHint':'Drag a clip onto a track to add it','media.dropDenied':'Only video / image / audio can be dropped here','media.added':'Clip added',
      'voice.title':'Voiceover','voice.gen':'Generate Voice','voice.voices':'Voice','voice.speed':'Speed','voice.pitch':'Pitch','voice.listen':'Listen','voice.stop':'Stop','voice.notConfig':'TTS Provider not configured. Configure it in Settings.','voice.mock':'DEV MOCK — estimated duration; listen uses browser Speech Synthesis.','voice.seg':'Segment','voice.cache':'Reused cached voice','voice.regen':'Regenerate Voice','voice.dur':'Voice duration','voice.listenText':'Hi, this is a voice preview. Pick the voice that suits your video by tone and pace.','voice.playFail':'Playback failed',
      'sub.title':'Subtitles','sub.style':'Style','sub.highlight':'Highlight keywords','sub.font':'Font','sub.size':'Size','sub.weight':'Weight','sub.color':'Color','sub.pos':'Position','sub.anim':'Animation','sub.st.Default':'Default','sub.st.Clean':'Clean','sub.st.Highlight':'Highlight','sub.st.Minimal':'Minimal','sub.st.editorial':'Editorial','sub.st.clean':'Clean Knowledge','sub.st.highlight':'Keyword Highlight','sub.st.cinematic':'Cinematic','sub.st.documentary':'Documentary','sub.st.tech':'Tech / Mono','sub.anim.none':'None','sub.anim.fade':'Fade','sub.anim.rise':'Rise','sub.anim.pop':'Pop','sub.safe':'Safe area',
      'ws.tabsScript':'SCRIPT','ws.tabsMedia':'MEDIA','ws.tabsVoice':'VOICE','ws.inspector':'INSPECTOR','ws.timeline':'TIMELINE','ws.noSel':'Select a clip','ws.none':'Nothing selected',
      'ws.tr.video':'VIDEO','ws.tr.voice':'VOICE','ws.tr.subtitle':'SUBTITLE','ws.tr.marker':'MARKER',
      'ws.video':'Video','ws.image':'Image','ws.audio':'Audio','ws.clip':'Clip','ws.source':'Source','ws.start':'Start','ws.end':'End','ws.scale':'Scale','ws.position':'Position','ws.crop':'Crop','ws.opacity':'Opacity','ws.rotation':'Rotation','ws.speed':'Speed','ws.volume':'Volume','ws.text':'Text','ws.line':'Line break','ws.bg':'Background','ws.shadow':'Shadow','ws.replace':'Replace','ws.replaced':'Clip replaced','ws.trimmed':'Trimmed','ws.split':'Split','ws.splitAt':'Split at playhead','ws.deleted':'Clip deleted','ws.moved':'Moved','ws.duplicated':'Clip duplicated','ws.muted':'Muted','ws.locked':'Locked',
      'ws.reason':'Matched because','ws.confidence':'Confidence','ws.low':'Low confidence','ws.weak':'Weak match','ws.recommended':'Recommended media','ws.regenVisual':'Regenerate Visual','ws.regenVoice':'Regenerate Voice','ws.regenAll':'Regenerate All','ws.regenDone':'Scene regenerated','ws.playhead':'Playhead','ws.align':'Align','ws.custom':'Custom','ws.copied':'Clip copied','tl.marker':'Marker','tl.markerAdded':'Marker added','tl.markerFail':'No scene at playhead',
      'ae.cta':'Auto Edit','ae.running':'Auto Edit in progress…','ae.stage.script':'Analyzing script…','ae.stage.voice':'Generating voice…','ae.stage.match':'Matching visuals…','ae.stage.timeline':'Building timeline…','ae.stage.subtitle':'Generating subtitles…','ae.stage.preview':'Rendering preview…','ae.stage.done':'Ready','ae.cancel':'Cancel','ae.cancelled':'Auto edit cancelled','ae.failed':'Auto edit failed','ae.retry':'Retry','ae.skip':'Skip','ae.assetFailed':'Asset analysis failed','ae.noMatch':'No strong visual match','ae.bestAvailable':'Use best available','ae.leaveEmpty':'Leave empty','ae.version':'Version','ae.style':'Editing Style','ae.quality':'Cut review','ae.overused':'used too often','ae.coldStart':'Opening has no footage',
      'exp.title':'Export','exp.mp4':'Export MP4','exp.srt':'Export SRT','exp.voice':'Export Voice','exp.res':'Resolution','exp.fps':'FPS','exp.bitrate':'Bitrate','exp.format':'Format','exp.start':'Export','exp.cancel':'Cancel','exp.progress':'Preparing','exp.stage.render':'Rendering','exp.stage.enc':'Encoding','exp.stage.final':'Finalizing','exp.stage.dl':'Download','exp.complete':'Export Complete','exp.dl':'Download MP4','exp.file':'File','exp.unavailable':'Export unavailable in this browser.','exp.reason':'Reason','exp.disabled.missing':'Missing assets or voice — fix before exporting','exp.disabled.invalid':'Timeline is invalid — fix before exporting','exp.dur':'Duration','exp.est':'Estimated','exp.srtDone':'SRT exported','exp.voiceUnavail':'Voice export needs a real TTS provider (no audio was rendered in DEV MOCK).','exp.noAudio':'Rendered without audio — DEV MOCK voice has no real audio. Configure a TTS provider for voice.','exp.verified':'verified',
      'set.title':'Settings','set.ai':'AI Analysis','set.ai.desc':'Provider for media & script understanding','set.aiProvider':'Provider','set.aiEndpoint':'API Endpoint','set.aiKey':'API Key','set.aiModel':'Model','set.tts':'TTS Voice','set.tts.desc':'Provider for voiceover generation','set.ttsProvider':'Provider','set.ttsEndpoint':'API Endpoint','set.ttsKey':'API Key','set.ttsVoice':'Default Voice','set.save':'Save Settings','set.saved':'Settings saved','set.mock':'Development Mock','set.mock.desc':'No provider configured — DEV MOCK is active. Real AI/TTS require a provider.','set.provider.none':'None (DEV MOCK)','set.provider.openai':'OpenAI Compatible','set.provider.custom':'Custom API','set.shortcuts':'Keyboard Shortcuts','set.shortcuts.desc':'Workspace shortcuts. They are disabled while you are typing in a text field.','kbd.play':'Play / Pause','kbd.undo':'Undo','kbd.redo':'Redo','kbd.save':'Save project','kbd.copy':'Copy clip','kbd.paste':'Paste clip','kbd.dup':'Duplicate clip','kbd.delete':'Delete clip','kbd.split':'Split at playhead','kbd.prevFrame':'Previous frame','kbd.nextFrame':'Next frame','kbd.seekBack':'Back 1 second','kbd.seekFwd':'Forward 1 second','kbd.home':'Go to start','kbd.end':'Go to end','kbd.marker':'Add marker','kbd.zoom':'Zoom timeline','kbd.fit':'Fit timeline','kbd.deselect':'Deselect',
      'err.generic':'Something went wrong','err.try':'Try again','err.404':'Not found','err.route':'This route does not exist.','err.home':'Back to home',
      'toast.saved':'Saved','toast.saveFailed':'Save failed','toast.restored':'Restored your last project','toast.deleted':'Deleted'
    },
    zh: {
      'app.name':'VIDEO LAB','app.tag':'AUTO EDIT',
      'nav.projects':'项目','nav.assets':'素材','nav.new':'新建剪辑','nav.settings':'设置',
      'cmd.search':'搜索命令…','cmd.save':'保存项目','cmd.export':'导出项目','cmd.openRecent':'打开最近项目','cmd.lang':'切换语言',
      'home.title':'Create a video.','home.sub':'文案 + 素材 → 自动成片。','home.newProj':'开始新项目','home.recent':'最近项目','home.empty':'还没有项目','home.emptySub':'创建你的第一条自动剪辑视频。','home.start':'创建第一条视频',
      'home.how':'工作原理','home.h1':'01 · 粘贴文案','home.h1d':'把文案交给我们，自动拆成场景。','home.h2':'02 · 上传素材','home.h2d':'拖入视频、图片或音频。','home.h3':'03 · 自动剪辑','home.h3d':'自动匹配、剪辑、配音、字幕。',
      'proj.open':'打开','proj.dup':'复制','proj.del':'删除','proj.untitled':'未命名项目','proj.thumb':'暂无预览','proj.badData':'项目加载失败','proj.delToast':'项目已删除','proj.dupToast':'项目已复制',
      'create.title':'新建剪辑','create.name':'项目名称','create.ratio':'视频比例','create.ratio.hint':'信息流推荐 9:16（抖音 / Reels / Shorts / 视频号）','create.start':'创建项目',
      'step.script':'文案','step.media':'素材','step.voice':'配音','step.auto':'自动剪辑','step.workspace':'工作台',
      'sc.paste':'粘贴你的文案','sc.placeholder':'在此粘贴文案…\n\n为什么很多人明明睡了 8 个小时，白天还是觉得很累？\n第一个原因，是你的睡眠质量可能并不好。\n第二个原因，是白天长时间保持高强度工作，大脑没有真正得到休息。\n所以，比单纯增加睡眠时间更重要的，是提高睡眠质量和白天的恢复效率。','sc.analyze':'分析文案','sc.scene':'场景','sc.keywords':'关键词','sc.intent':'意图','sc.visual':'画面建议','sc.dur':'时长','sc.editText':'编辑文案','sc.noScenes':'还没有场景 — 粘贴文案后点击「分析文案」。',
      'media.title':'你的素材','media.drop':'拖拽文件到这里','media.dropSub':'MP4 · MOV · WebM · JPG · PNG · WebP · MP3 · WAV','media.upload':'上传素材','media.list':'素材库','media.selected':'已选素材','media.analyze':'分析素材','media.analyzing':'分析中…','media.noAssets':'还没有素材。拖入文件或点击上传。','media.asset':'素材','media.basic':'基本信息','media.semantic':'语义标签','media.tags':'标签','media.mock':'开发模式（Mock）分析','media.notConfig':'AI 分析未配置。请在设置中配置分析 Provider。','media.preview':'预览','media.remove':'移除','media.error.size':'文件过大（视频 200MB 以内，图片/音频 50MB 以内）。','media.error.type':'不支持的文件格式。','media.error.read':'无法读取该文件，可能已损坏。','media.analyzeDone':'素材分析完成','media.dragHint':'把素材拖到时间轴轨道上即可添加','media.dropDenied':'只有视频 / 图片 / 音频可以拖入该轨道','media.added':'已添加片段',
      'voice.title':'配音','voice.gen':'生成配音','voice.voices':'声音','voice.speed':'语速','voice.pitch':'音调','voice.listen':'试听','voice.stop':'停止','voice.notConfig':'TTS Provider 未配置。请在设置中配置。','voice.mock':'开发模式（Mock）— 时长为估算值；试听使用浏览器语音合成。','voice.seg':'片段','voice.cache':'已复用缓存配音','voice.regen':'重新生成配音','voice.dur':'配音时长','voice.listenText':'你好，这是一段配音试听。你可以根据语速、音色和自然程度，选择适合这条视频的声音。','voice.playFail':'无法播放试听',
      'sub.title':'字幕','sub.style':'样式','sub.highlight':'关键词高亮','sub.font':'字体','sub.size':'字号','sub.weight':'字重','sub.color':'颜色','sub.pos':'位置','sub.anim':'动画','sub.st.Default':'默认','sub.st.Clean':'简洁','sub.st.Highlight':'高亮','sub.st.Minimal':'极简','sub.st.editorial':'编辑式','sub.st.clean':'知识简洁','sub.st.highlight':'关键词高亮','sub.st.cinematic':'电影感','sub.st.documentary':'纪实','sub.st.tech':'科技等宽','sub.anim.none':'无','sub.anim.fade':'淡入','sub.anim.rise':'上浮','sub.anim.pop':'弹出','sub.safe':'安全区',
      'ws.tabsScript':'脚本','ws.tabsMedia':'素材','ws.tabsVoice':'配音','ws.inspector':'检查器','ws.timeline':'时间轴','ws.noSel':'选择一个片段','ws.none':'未选择',
      'ws.tr.video':'视频','ws.tr.voice':'配音','ws.tr.subtitle':'字幕','ws.tr.marker':'标记',
      'ws.video':'视频','ws.image':'图片','ws.audio':'音频','ws.clip':'片段','ws.source':'源','ws.start':'开始','ws.end':'结束','ws.scale':'缩放','ws.position':'位置','ws.crop':'裁切','ws.opacity':'不透明度','ws.rotation':'旋转','ws.speed':'速度','ws.volume':'音量','ws.text':'文字','ws.line':'换行','ws.bg':'背景','ws.shadow':'阴影','ws.replace':'替换','ws.replaced':'片段已替换','ws.trimmed':'已修剪','ws.split':'分割','ws.splitAt':'在播放头处分割','ws.deleted':'片段已删除','ws.moved':'已移动','ws.duplicated':'片段已复制','ws.muted':'已静音','ws.locked':'已锁定',
      'ws.reason':'匹配原因','ws.confidence':'置信度','ws.low':'低置信度','ws.weak':'弱匹配','ws.recommended':'推荐素材','ws.regenVisual':'重新匹配画面','ws.regenVoice':'重新生成配音','ws.regenAll':'重新自动剪辑','ws.regenDone':'场景已重新生成','ws.playhead':'播放头','ws.align':'对齐','ws.custom':'自定义','ws.copied':'片段已复制','tl.marker':'标记','tl.markerAdded':'标记已添加','tl.markerFail':'播放头处没有场景',
      'ae.cta':'自动剪辑','ae.running':'自动剪辑进行中…','ae.stage.script':'正在分析文案…','ae.stage.voice':'正在生成配音…','ae.stage.match':'正在匹配画面…','ae.stage.timeline':'正在构建时间轴…','ae.stage.subtitle':'正在生成字幕…','ae.stage.preview':'正在渲染预览…','ae.stage.done':'完成','ae.cancel':'取消','ae.cancelled':'已取消自动剪辑','ae.failed':'自动剪辑失败','ae.retry':'重试','ae.skip':'跳过','ae.assetFailed':'素材分析失败','ae.noMatch':'没有强匹配的画面','ae.bestAvailable':'使用最佳可用素材','ae.leaveEmpty':'留空','ae.version':'版本','ae.style':'剪辑风格','ae.quality':'成片检查','ae.overused':'重复使用过多','ae.coldStart':'开头缺少画面',
      'exp.title':'导出','exp.mp4':'导出 MP4','exp.srt':'导出 SRT','exp.voice':'导出配音','exp.res':'分辨率','exp.fps':'帧率','exp.bitrate':'码率','exp.format':'格式','exp.start':'导出','exp.cancel':'取消','exp.progress':'准备中','exp.stage.render':'渲染','exp.stage.enc':'编码','exp.stage.final':'封装','exp.stage.dl':'下载','exp.complete':'导出完成','exp.dl':'下载 MP4','exp.file':'文件','exp.unavailable':'当前浏览器无法导出。','exp.reason':'原因','exp.disabled.missing':'存在缺失的素材或配音 — 修复后才能导出','exp.disabled.invalid':'时间轴无效 — 修复后才能导出','exp.dur':'时长','exp.est':'预估','exp.srtDone':'SRT 已导出','exp.voiceUnavail':'配音导出需要真实 TTS Provider（开发模式下未渲染真实音频）。','exp.noAudio':'本次导出无音轨 — 开发模式下配音为估算时长。配置 TTS Provider 后才有真实人声。','exp.verified':'已验证',
      'set.title':'设置','set.ai':'AI 分析','set.ai.desc':'素材与文案理解的 Provider','set.aiProvider':'Provider','set.aiEndpoint':'API 地址','set.aiKey':'API Key','set.aiModel':'模型','set.tts':'TTS 配音','set.tts.desc':'配音生成的 Provider','set.ttsProvider':'Provider','set.ttsEndpoint':'API 地址','set.ttsKey':'API Key','set.ttsVoice':'默认声音','set.save':'保存设置','set.saved':'设置已保存','set.mock':'开发模式（Mock）','set.mock.desc':'未配置任何 Provider — 当前为开发模式。接入真实 AI/TTS 需要配置 Provider。','set.provider.none':'无（开发模式）','set.provider.openai':'OpenAI 兼容','set.provider.custom':'自定义 API','set.shortcuts':'快捷键','set.shortcuts.desc':'工作台快捷键。在文字输入框内输入时会自动停用。','kbd.play':'播放 / 暂停','kbd.undo':'撤销','kbd.redo':'重做','kbd.save':'保存项目','kbd.copy':'复制片段','kbd.paste':'粘贴片段','kbd.dup':'复制为新片段','kbd.delete':'删除片段','kbd.split':'在播放头处分割','kbd.prevFrame':'上一帧','kbd.nextFrame':'下一帧','kbd.seekBack':'后退 1 秒','kbd.seekFwd':'前进 1 秒','kbd.home':'跳转到开头','kbd.end':'跳转到结尾','kbd.marker':'添加标记','kbd.zoom':'缩放时间轴','kbd.fit':'适配时间轴','kbd.deselect':'取消选择',
      'err.generic':'出现了一点问题','err.try':'重试','err.404':'页面不存在','err.route':'该路由不存在。','err.home':'返回首页',
      'toast.saved':'已保存','toast.saveFailed':'保存失败','toast.restored':'已恢复最近的项目','toast.deleted':'已删除'
    }
  };
  let lang = 'zh';
  try{ const saved = localStorage.getItem('motionlab.lang'); if(saved==='en'||saved==='zh') lang = saved; }catch(e){}
  function t(key){
    const en = DICT.en[key], zh = DICT.zh[key];
    if(lang==='en') return en !== undefined ? en : (zh !== undefined ? zh : key);
    return zh !== undefined ? zh : (en !== undefined ? en : key);
  }
  function set(l){ lang = (l==='en'||l==='zh')?l:'zh'; try{ localStorage.setItem('motionlab.lang', lang); }catch(e){} }
  return { t, set, get lang(){ return lang; } };
})();
